substitutions: !include ../common/subs.yaml

esphome:  
  min_version: ${esphome_min_version}
  friendly_name: "${friendly_name}"
  name: "${device_name}"
  comment: "${comment_description} | IP ${static_ip_address} | v${project_version}"
  project:
    name: ${project_name}
    version: ${project_version}
  name_add_mac_suffix: false